### ISSUE TITLE
Sparkfun Quad Solid State library -fpermissive issue

### ISSUE THREAD

**Issue by PickyBiker** [sparkfun/SparkFun_Qwiic_Relay_Arduino_Library#1]
The Quad Solid State library Example2_Quad_Relay_Basics sketch compiles without errors or warnings using the Arduino UNO in the Arduino IDE. That is because with that board in that IDE the -fpermissive compile flag is set by default.

If you try to compile that board using a Teensy board, the -fpermissive flag is not set and the compiler generates the numerous warnings. Please correct the code so it works without warnings when using Teensy boards.

In addition, the default I2C address is "RELAY_ADDR 0x6D // Alternate address 0x6C" but when an I2C scan is performed the actual board address (just purchased and unaltered) appears to be 0x08.

Here is the environment being used:
OS: Windows 10
IDE: Arduino version 1.8.12
Boards: Arduino UNO and Teensy 4.0
SparkFun_Qwiic_Relay library 1.2.0
The Quad Relay board is the one in this kit  https://www.sparkfun.com/products/16833

The warnings are cause by 2 lines of code in the SparkFun_Qwiic_Relay.cpp file. The changes I tested (shown below) resolve the warnings issue but you may want to apply a different fix.

line #340 original _i2cPort->requestFrom(_address, 1);
line #340 no warnings with: _i2cPort->requestFrom((uint16_t)_address, 1);

line #353 original: _i2cPort->requestFrom(_address, 2);
line #353 no warnings with: _i2cPort->requestFrom((uint16_t)_address, 2);

The requestFrom function expects the address argument to be a 16 bit value but _address is an 8 bit value. Without -fpermissive this generates the warnings.

The warnings are in this attached file.
[Errors.txt](https://github.com/sparkfun/SparkFun_Qwiic_Relay_Arduino_Library/files/5022571/Errors.txt)

**Comment by thorathome** [comment]
Hiya Sparkfun. I get the same warnings using
- Arduino IDE 2.0.3 with Default compiler warnings, no verbose selected
- Sparkfun Qwiic Relay Arduino Library v 1.2.0
- Win 11 Pro
- Compiling to ESP32 and ESP8266

Yes, the library works fine and the sketch still compiles. Thanks. 
And the Solid State Quad Relay kit really is a marvel. I'm building a project around it now - works well.  

However, these multiple compiler warnings, the only ones I regularly see, do not reflect well on the Sparkfun brand. 
And if these warnings are MY fault, it doesn't reflect well on my brand! 

If this is easy to fix, it's worth doing, imho. 

Happy to help and test if appropriate. Thanks in advance. Very nice product.  
Thanks.

```
c:\Users\thor\Dropbox\My Documents\Arduino\libraries\Sparkfun_Qwiic_Relay_Library\src\SparkFun_Qwiic_Relay.cpp: In member function 'uint8_t Qwiic_Relay::_readCommand(uint8_t)':
c:\Users\thor\Dropbox\My Documents\Arduino\libraries\Sparkfun_Qwiic_Relay_Library\src\SparkFun_Qwiic_Relay.cpp:340:36: warning: ISO C++ says that these are ambiguous, even though the worst conversion for the first is better than the worst conversion for the second:
   _i2cPort->requestFrom(_address, 1);
                                    ^
In file included from c:\Users\thor\Dropbox\My Documents\Arduino\libraries\Sparkfun_Qwiic_Relay_Library\src\SparkFun_Qwiic_Relay.h:4,
                 from c:\Users\thor\Dropbox\My Documents\Arduino\libraries\Sparkfun_Qwiic_Relay_Library\src\SparkFun_Qwiic_Relay.cpp:12:
C:\Users\thor\AppData\Local\Arduino15\packages\esp32\hardware\esp32\2.0.6\libraries\Wire\src/Wire.h:127:13: note: candidate 1: 'uint8_t TwoWire::requestFrom(int, int)'
     uint8_t requestFrom(int address, int size);
             ^~~~~~~~~~~
C:\Users\thor\AppData\Local\Arduino15\packages\esp32\hardware\esp32\2.0.6\libraries\Wire\src/Wire.h:125:13: note: candidate 2: 'uint8_t TwoWire::requestFrom(uint8_t, uint8_t)'
     uint8_t requestFrom(uint8_t address, uint8_t size);
             ^~~~~~~~~~~
c:\Users\thor\Dropbox\My Documents\Arduino\libraries\Sparkfun_Qwiic_Relay_Library\src\SparkFun_Qwiic_Relay.cpp: In member function 'float Qwiic_Relay::_readVersion(uint8_t)':
c:\Users\thor\Dropbox\My Documents\Arduino\libraries\Sparkfun_Qwiic_Relay_Library\src\SparkFun_Qwiic_Relay.cpp:353:36: warning: ISO C++ says that these are ambiguous, even though the worst conversion for the first is better than the worst conversion for the second:
   _i2cPort->requestFrom(_address, 2);
                                    ^
In file included from c:\Users\thor\Dropbox\My Documents\Arduino\libraries\Sparkfun_Qwiic_Relay_Library\src\SparkFun_Qwiic_Relay.h:4,
                 from c:\Users\thor\Dropbox\My Documents\Arduino\libraries\Sparkfun_Qwiic_Relay_Library\src\SparkFun_Qwiic_Relay.cpp:12:
C:\Users\thor\AppData\Local\Arduino15\packages\esp32\hardware\esp32\2.0.6\libraries\Wire\src/Wire.h:127:13: note: candidate 1: 'uint8_t TwoWire::requestFrom(int, int)'
     uint8_t requestFrom(int address, int size);
             ^~~~~~~~~~~
C:\Users\thor\AppData\Local\Arduino15\packages\esp32\hardware\esp32\2.0.6\libraries\Wire\src/Wire.h:125:13: note: candidate 2: 'uint8_t TwoWire::requestFrom(uint8_t, uint8_t)'
     uint8_t requestFrom(uint8_t address, uint8_t size);
             ^~~~~~~~~~~

```

**Comment by edspark** [comment]
The `requestFrom()` ambiguity error has been fixed in the latest release. Sorry for the delay.
