### ISSUE TITLE
Collision between Sparkfun QWIIC Relay Library and QWIIC Serial Motor Library

### ISSUE THREAD

**Issue by DavidArmstrong** [sparkfun/SparkFun_Qwiic_Relay_Arduino_Library#4]
I've discovered that if I use the two Sparkfun libraries for the QWIIC Relay, and the QWIIC Serial Motor Controller, that the two collide when defined as follows in a sketch:

// Test sketch demonstrating collision between Sparkfun
// QWICC Relay library and QWIIC Serial Motor Control Library

#include <Arduino.h>
#include "pins_arduino.h"
#include <Wire.h>  // Include Wire if you're using I2C

#include "SCMD.h" // Serial Controlled Motor Driver https://github.com/sparkfun/Serial_Controlled_Motor_Driver
#include "SCMD_config.h" //Contains #defines for common SCMD register names and values
#include "SparkFun_Qwiic_Relay.h"  // https://github.com/sparkfun/SparkFun_Qwiic_Relay_Arduino_Library

#define RELAY_ADDR 0x18 // Alternate address 0x19

SCMD i2cMotorDriver; //Serial Controlled Motor Driver
Qwiic_Relay relay(RELAY_ADDR);

void setup() {
  // put your setup code here, to run once:

}

void loop() {
  // put your main code here, to run repeatedly:
  while(1) ;
}

Yet, if I switch the order that the libraries are referenced in the sketch, then it compiles fine.  So, while there is a workaround for this issue, it could lead to some 'head scratching' as to what happened.

For completeness, I'll quote the error response that the Arduino IDE gives me below:

Arduino: 1.8.15 (Windows 10), Board: "SparkFun RedBoard Turbo"

In file included from C:\Users\Keiichi\Documents\Arduino\libraries\Serial_Controlled_Motor_Driver\src/SCMD.h:26:0,

                 from C:\Users\Keiichi\Documents\Arduino\SparkfunCollision\SparkfunCollision.ino:8:

C:\Users\Keiichi\Documents\Arduino\libraries\Serial_Controlled_Motor_Driver\src/SCMD_config.h:27:36: error: expected identifier before numeric constant

 #define FIRMWARE_VERSION           0x07

                                    ^

C:\Users\Keiichi\Documents\Arduino\libraries\SparkFun_Qwiic_Relay_Arduino_Library\src/SparkFun_Qwiic_Relay.h:46:3: note: in expansion of macro 'FIRMWARE_VERSION'

   FIRMWARE_VERSION    = 0x04,

   ^

C:\Users\Keiichi\Documents\Arduino\libraries\Serial_Controlled_Motor_Driver\src/SCMD_config.h:27:36: error: expected '}' before numeric constant

 #define FIRMWARE_VERSION           0x07

                                    ^

C:\Users\Keiichi\Documents\Arduino\libraries\SparkFun_Qwiic_Relay_Arduino_Library\src/SparkFun_Qwiic_Relay.h:46:3: note: in expansion of macro 'FIRMWARE_VERSION'

   FIRMWARE_VERSION    = 0x04,

   ^

C:\Users\Keiichi\Documents\Arduino\libraries\Serial_Controlled_Motor_Driver\src/SCMD_config.h:27:36: error: expected unqualified-id before numeric constant

 #define FIRMWARE_VERSION           0x07

                                    ^

C:\Users\Keiichi\Documents\Arduino\libraries\SparkFun_Qwiic_Relay_Arduino_Library\src/SparkFun_Qwiic_Relay.h:46:3: note: in expansion of macro 'FIRMWARE_VERSION'

   FIRMWARE_VERSION    = 0x04,

   ^

In file included from C:\Users\Keiichi\Documents\Arduino\SparkfunCollision\SparkfunCollision.ino:10:0:

C:\Users\Keiichi\Documents\Arduino\libraries\SparkFun_Qwiic_Relay_Arduino_Library\src/SparkFun_Qwiic_Relay.h:49:1: error: expected declaration before '}' token

 };

 ^

exit status 1

Error compiling for board SparkFun RedBoard Turbo.

This report would have more information with
"Show verbose output during compilation"
option enabled in File -> Preferences.

**Comment by edspark** [comment]
Ah, thank you for filing an issue - fixed!
